---
title: "Fast and kind API queries with `shiny::bindCache()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Summary

Here we demonstrate the use of the new `bindCache()` function in Shiny to greatly speedup a Shiny app that queries an NOAA weather station data API. The use of caching not only speeds up the app for end users but relieves pressure from the API. In this post we will demonstrate the adding of `bindCache` to existing reactive expressions, explaining where and why it should be used along with some potential gotchas of doing so. 


## Demo App

### NOAA Temperature Normals
- Weather station data on temp and precipitataion
- 1981-2010
- Gives "normal" or "average" weather

### Inspiration for app
- NYT how much hotter was your city story
- Holistic view of weather

### App flow

- Current city
  - Downloads all stations within city's data
- Two semi-complicated plots for temperature and precipitation
- Previous city button for comparisons

## Performance with vanilla app
- Slow due to long process of gathering data for a city and potential slow server responses

## Adding Caching
- Just add `bindCache()` to all the complex reactives

## Performance with caching
- Biggest difference seen when toggling back and forth
  
## Tuning Caching
- Disk cache
- App cache
  - Will speed up app for future user's too
  - Common cities will be almost instant
- Cache size

## `bindCache()` vs `renderCachedPlot()`
- They're the same

